### ISSUE TITLE
Inject node set msg property uses synchronous context calls

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/nr-persistent-context#16]
### Current Behavior

If you ask the core Node-RED Inject node to set a msg property to a value from the persistent context it uses synchronous call to the `context.get()` method.

Since this context implementation doesn't currently support synchronous usage it crashes the Node-RED project

### Expected Behavior

Inject node to be able to set a msg property to a value from the persistent context

### Steps To Reproduce

- Create a project
- Add inject node
- Set msg.payload to `global.foo` from the persistent context
- Deploy
- Trigger Inject node

### Environment

- FlowForge version: 1.2
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Kubernetes/Linux
- Browser: Any

**Comment by hardillb** [comment]
Upstream: https://github.com/node-red/node-red/issues/4014

**Comment by knolleary** [comment]
Upstream issue fixed in NR 3.1
